### ISSUE TITLE
Can't install jest-stare

### ISSUE THREAD

**Issue by azakordonets** [dkelosky/jest-stare#370]
Hi, sorry if my problem will be a simple stupid, but I can't figure out why I'm having troubles with installing your package. When i add it to my Typescript project, I get : 
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: shaven@0.8.1
npm ERR! notsup Not compatible with your version of node/npm: shaven@0.8.1
npm ERR! notsup Required: {"node":"~0.12.2"}
npm ERR! notsup Actual:   {"npm":"7.3.0","node":"v12.13.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2020-12-30T23_54_18_465Z-debug.log
```

In the debug log i see this : 
```
5593 verbose stack Error: Unsupported engine
5593 verbose stack     at checkEngine (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-install-checks/index.js:15:25)
5593 verbose stack     at c (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:240:21)
5593 verbose stack     at Arborist.[checkEngine] (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:243:7)
5593 verbose stack     at /Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:227:31
5593 verbose stack     at async Arborist.buildIdealTree (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:212:7)
5593 verbose stack     at async Promise.all (index 1)
5593 verbose stack     at async Arborist.reify (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:123:5)
5593 verbose stack     at async install (/Users/andrew/.nvm/versions/node/v12.13.1/lib/node_modules/npm/lib/install.js:38:3)
5594 verbose pkgid shaven@0.8.1
5595 verbose cwd /Users/andrew/Work/New10/Testing/contract-testing/mediator
5596 verbose Darwin 20.2.0
5597 verbose argv "/Users/andrew/.nvm/versions/node/v12.13.1/bin/node" "/Users/andrew/.nvm/versions/node/v12.13.1/bin/npm" "install"
5598 verbose node v12.13.1
5599 verbose npm  v7.3.0
5600 error code EBADENGINE
5601 error engine Unsupported engine
5602 error engine Not compatible with your version of node/npm: shaven@0.8.1
5603 error notsup Not compatible with your version of node/npm: shaven@0.8.1
5603 error notsup Required: {"node":"~0.12.2"}
5603 error notsup Actual:   {"npm":"7.3.0","node":"v12.13.1"}
5604 verbose exit 1
```

I'm really surprised that such old version of node and package is used somewhere down the dependency tree. Have you seen such problem before ?

**Comment by dkelosky** [comment]
Hey, does this only happen installing jest-stare or some other package?  I haven't seen this, but perhaps there is an issue somewhere.  Can you share your package.json?

**Comment by azakordonets** [comment]
Yeah, it happens only when i add `jest-stare` dependency to my project. Sorry for not posting the package.json right away : 
```
{

  "scripts": {
    "dev": "ts-node src/cli.ts",
    "clean": "rimraf ./dist/ ./bin/",
    "check-node-version": "check-node-version --node 12",
    "prebuild": "npm run check-node-version",
    "build": "npm run clean && node_modules/typescript/bin/tsc -p src/tsconfig.json",
    "bundle": "npm run build && node node_modules/pkg/lib-es5/bin.js . --out-dir bin --targets node12-linux-x64,node12-macos-x64",
    "pretest": "npm run check-node-version",
    "test": "npm run clean && jest",
    "test:compact": "npm run test -- --config jest.silent.config.js --coverage=true",
    "test:coverage": "npm test -- --coverage=true",
    "check:types": "node_modules/typescript/bin/tsc -p src/tsconfig.json",
    "format": "prettier \"**/*.{ts,tsx,js,jsx,yml,yaml}\" --ignore-path .gitignore --write",
    "prettier": "prettier \"**/*.{ts,tsx,js,jsx,yml,yaml}\" --ignore-path .prettierignore --check",
    "fix": "npm run format && npm run lint --fix",
    "lint": "eslint . --ignore-path .gitignore --resolve-plugins-relative-to .",
    "release": "npm run build && semantic-release",
    "release:dry": "npm run build && semantic-release --dry-run"
  },
  "devDependencies": {
    "@types/cli-table": "^0.3.0",
    "@types/deep-diff": "^1.0.0",
    "@types/json-schema-faker": "^0.5.1",
    "@types/lodash": "^4.14.165",
    "@types/mime-types": "^2.1.0",
    "@types/rimraf": "^3.0.0",
    "@types/shelljs": "^0.8.8",
    "@types/to-json-schema": "^0.2.0",
    "babel-eslint": "^10.0.3",
    "check-node-version": "^4.0.3",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-functional": "^3.1.0",
    "jest": "^26.6.3",
    "jest-expect-message": "^1.0.2",
    "jest-silent-reporter": "^0.4.0",
    "lodash": "^4.17.20",
    "mime-types": "^2.1.27",
    "pkg": "^4.4.0",
    "prettier-eslint": "^9.0.0",
    "rimraf": "^2.6.3",
    "semantic-release": "^17.3.1",
    "to-json-schema": "^0.2.5",
    "ts-jest": "^26.4.4",
    "ts-node": "^9.1.1",
    "typedoc": "^0.20.5",
    "typescript": "^4.0.3",
    "jest-stare": "^2.2.0"
  },
  "dependencies": {
    "ajv": "^6.12.6",
    "aws-sdk": "^2.797.0",
    "chalk": "^4.1.0",
    "cli-table": "^0.3.1",
    "commander": "^6.2.0",
    "deep-diff": "^1.0.2",
    "figlet": "^1.5.0",
    "json-schema-faker": "^0.5.0-rcv.32",
    "shelljs": "^0.8.4",
    "tslib": "^1.14.1",
    "typescript-json-schema-faker": "^0.0.10"
  },
  "types": "index.d.ts"
}
```

**Comment by azakordonets** [comment]
I actually tried to pull this package.json into a small repo for better reprocubility, but i get weird results - sometimes it goes fine with fresh install, sometimes it fails. Since i can't give you 100% reproducibility right now, i will close this ticket and will get back to you when i find 100% case. Sorry for taking your time and thanks for building such a cool reporter.

**Comment by dkelosky** [comment]
Np, please let me know if you pin it down to this project. 

Thanks & take care
